- name: Setup roboshop project
  hosts: FRONTEND
  become: yes
  roles:
    -name: Load Frontend Role
      role: frontend

#- name: setup roboshop project
#  hosts: MongoDB
#  roles:
#    -name: Load MongoDb role
#    role: mongodb


